# Generated by Django 4.2.2 on 2023-06-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0002_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='image_url',
            field=models.URLField(verbose_name='Link to Image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_url',
            field=models.URLField(verbose_name='Link to Profile Image'),
        ),
    ]
