# Generated by Django 4.2.2 on 2023-06-15 05:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesplay_app', '0002_gamemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodel',
            name='max_level',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
