# Generated by Django 4.2.2 on 2023-06-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesplay_app', '0003_alter_gamemodel_max_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='password',
            field=models.CharField(default='fake', max_length=30),
            preserve_default=False,
        ),
    ]
