# Generated by Django 4.2.2 on 2023-06-14 16:52

import django.core.validators
from django.db import migrations, models
import oct_30_2022.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_profile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Sports Car', 'Sports Car'), ('Pickup', 'Pickup'), ('Crossover', 'Crossover'), ('Minibus', 'Minibus'), ('Other', 'Other')], max_length=10)),
                ('model', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)])),
                ('year', models.IntegerField(validators=[oct_30_2022.web.validators.CheckIfYearInBetween(1980, 2049)])),
                ('image_url', models.URLField()),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
