# Generated by Django 4.2.2 on 2023-06-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_library', '0002_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_url',
            field=models.URLField(verbose_name='Image'),
        ),
    ]
