# Generated by Django 4.2.1 on 2023-06-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='first_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
