# Generated by Django 4.2.1 on 2023-06-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_alter_people_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='level',
            field=models.CharField(choices=[('Baby', 'Baby'), ('Teen', 'Teen'), ('Old', 'Old')], default='None', max_length=10),
        ),
    ]
