# Generated by Django 4.2.1 on 2023-06-01 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='city_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='demo.cities'),
            preserve_default=False,
        ),
    ]
