# Generated by Django 4.2.1 on 2023-06-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_people_city_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ['-age']},
        ),
        migrations.AddField(
            model_name='people',
            name='zodiac',
            field=models.CharField(default='null', max_length=10),
            preserve_default=False,
        ),
    ]
