# Generated by Django 4.2.3 on 2023-07-09 14:56

import cbv_demo.web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=30, validators=[cbv_demo.web.models.check_if_only_letters]),
        ),
    ]
