# Generated by Django 4.2.2 on 2023-06-24 06:48

import django.core.validators
from django.db import migrations, models
import fruitipedia.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FruitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), fruitipedia.web.validators.check_if_string_only_letters])),
                ('image_url', models.URLField(verbose_name='Image URL')),
                ('description', models.TextField()),
                ('nutrition', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
