# Generated by Django 4.2.2 on 2023-06-24 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_fruitmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fruitmodel',
            options={'ordering': ['pk']},
        ),
    ]
