# Generated by Django 4.2.2 on 2023-06-24 08:51

import django.core.validators
from django.db import migrations, models
import fruitipedia.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_fruitmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='first_name',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2), fruitipedia.web.validators.check_if_string_starts_with_letter], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='last_name',
            field=models.CharField(max_length=35, validators=[django.core.validators.MinLengthValidator(1), fruitipedia.web.validators.check_if_string_starts_with_letter], verbose_name='Last Name'),
        ),
    ]
