# Generated by Django 4.2.2 on 2023-06-13 10:58

import django.core.validators
from django.db import migrations, models
import feb_27_2022.web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), feb_27_2022.web.models.validate_only_alphanumeric]),
        ),
    ]
