# Generated by Django 4.2.2 on 2023-06-13 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_profile_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('pk',)},
        ),
        migrations.RenameField(
            model_name='album',
            old_name='name',
            new_name='album_name',
        ),
    ]
