# Generated by Django 4.2.1 on 2023-05-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_nullblankdemo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='us_full_time',
            field=models.BooleanField(null=True),
        ),
    ]
