# Generated by Django 4.2.1 on 2023-05-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_employee_us_full_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='level',
            field=models.CharField(choices=[('jr', 'Junior'), ('reg', 'Regular'), ('sr', 'Senior')], max_length=25),
        ),
    ]
