# Generated by Django 4.2.1 on 2023-05-30 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_department_alter_employee_email_alter_employee_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
    ]
